### ISSUE TITLE
Premenovanie repozitaru

### ISSUE THREAD

**Issue by fr6nco** [aks-2017/semestralne-zadania-semestralne-zadanie-xchalachan-xguran#1]
Ahojte,

zle som sa vyjadril v maili. Proism poslite mi vase x[meno] loginy ja updatenem meno timu a repozitaru. Budete musiet asi updatenut origin vo vasich gitoch.

Tomas

**Comment by macooonie** [comment]
Ahoj,
loginy su xchalachan a xguran.
Dakujeme
